# Generated by Django 6.0.1 on 2026-01-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('SMOKE', 'Smoke'), ('REGRESSION', 'Regression'), ('EDGE', 'Edge')], max_length=20)),
                ('priority', models.IntegerField(default=3)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='projects.service')),
            ],
        ),
    ]
