# Generated by Django 6.0.1 on 2026-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('UI', 'UI'), ('UNIT', 'UNIT'), ('API', 'API'), ('INTEGRATION', 'INTEGRATION')], max_length=20),
        ),
    ]
