# Generated by Django 6.0.1 on 2026-01-30 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('affected_tests', models.JSONField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_report', to='changes.change')),
            ],
        ),
    ]
